apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo
  namespace: mongo-ns
spec:

  # Mount path of the secrets backend
  mount: mongodb
  namespace: dev
  # Path to the secret
  path: creds/dev-mongodb

  # Where to store the secrets, end user will create the secret
  destination:
    create: false
    name: vso-db-demo

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: vso-db-demo

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth-mongo