---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: static-ns
  name: static-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dynamic-auth
  namespace: static-ns
spec:
  method: kubernetes
  mount: demo-auth-mount
  namespace: dev
  kubernetes:
    role: auth-role-static
    serviceAccount: static-app
    audiences:
      - vault