apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-static
  namespace: static-ns
spec:

  # Mount path of the secrets backend
  mount: mongodb
  namespace: dev
  # Path to the secret
  path: static-creds/dev-mongodb-static

  # Where to store the secrets, end user will create the secret
  destination:
    create: false
    name: vso-db-static

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: vso-db-static

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth